apiVersion: v1
kind: Service
metadata:
  name: lsk-core
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
    - name: lsk-port
      port: 8000
      targetPort: 800
      protocol: TCP
  selector:
    service: lsk-core
